// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBy1wKE_t4cKVBbeN0ef2rbclxizTK_Wc',
    appId: '1:446643918761:web:0788602ac47b926df6d6b8',
    messagingSenderId: '446643918761',
    projectId: 'granddesiparatha-967b5',
    authDomain: 'granddesiparatha-967b5.firebaseapp.com',
    storageBucket: 'granddesiparatha-967b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbtXMwZsU4joa5GuuOPkudoIFM3fGGYHs',
    appId: '1:446643918761:android:49df1f6600081217f6d6b8',
    messagingSenderId: '446643918761',
    projectId: 'granddesiparatha-967b5',
    storageBucket: 'granddesiparatha-967b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArKMktRlnEiQ5bN3n_GC8IFD_c2SS46Ds',
    appId: '1:446643918761:ios:571f0076be5829bef6d6b8',
    messagingSenderId: '446643918761',
    projectId: 'granddesiparatha-967b5',
    storageBucket: 'granddesiparatha-967b5.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );
}
